apiVersion: v1
stringData:
  azurestorageaccountkey: {{ .Values.persistence.azurefile.password }}
  azurestorageaccountname: {{ .Values.persistence.azurefile.name }}
kind: Secret
metadata:
  name: azurefile-secret
type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-data
spec:
  capacity:
    storage: {{ .Values.persistence.azurefile.size }}
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azurefile-secret
    secretNamespace: {{ .Release.Namespace }}
    shareName: {{ .Values.persistence.azurefile.shareName }}
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistence.azurefile.size }}